apiVersion: v1
kind: Service
metadata:
  name: {{ include "load-generator.fullname" . }}
  labels:
    {{- include "load-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "load-generator.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
