replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/customer-app/customer-api
  tag: "3080c196576fe2a0c180aa4111a043435869dc5b"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: ""

resources:
  requests:
    cpu: 60m
    memory: 163840Ki
  limits:
    cpu: 0m
    memory: 393216Ki
