replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/customer-app/customer-app
  tag: "ca3cc6efb6ff6f5cc6a62a29d15f8a6598479e34"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: ""

env:
  VITE_API_URL: "https://customer-api-customer-app.apps.itz-g7soj0.infra01-lb.dal14.techzone.ibm.com"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
