apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SysCarmenB/customer-app-gitops.git
    targetRevision: main
    path: helm/customer-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
