replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/customer-app/load-generator
  tag: "3080c196576fe2a0c180aa4111a043435869dc5b"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081

route:
  enabled: true
  host: ""

env:
  TARGET_URL: "http://customer-api:8080/api/customers"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
